/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : RDKAFKA
 #	author : miyako
 #	2017/11/20
 #
 # --------------------------------------------------------------------------------*/

#include "rdkafka.h"
#include "libjson.h"

#if VERSIONMAC
#include <sys/time.h>
#endif

// --- RDKAFKA
void KAFKA_Consume(sLONG_PTR *pResult, PackagePtr pParams);
void KAFKA_Produce(sLONG_PTR *pResult, PackagePtr pParams);
void KAFKA_Get_version(sLONG_PTR *pResult, PackagePtr pParams);
void KAFKA_Get_topics(sLONG_PTR *pResult, PackagePtr pParams);
void KAFKA_Get_groups(sLONG_PTR *pResult, PackagePtr pParams);

typedef struct
{
	int exit_eof;
	int wait_eof;
	int run;
	JSONNODE *json;
	rd_kafka_resp_err_t err;
}rd_opaque;
